services:
  frontend:
    build: frontend
    command: pnpm dev --host
    depends_on:
      - backend
    networks:
      - workout-tracker-net
    volumes:
      - ./frontend:/app
      #- /app/node_modules:/app/node_modules
    expose:
      - 5173
    ports:
      - 127.0.0.1:3001:5173

  backend:
    build: backend
    command: pnpm dev
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=postgresql://postgres:dev@db:5432/postgres
      - DB_CONNECTION_STRING=postgresql://postgres:dev@db:5432/wdb
      - DBNAME=wdb
      - JWT_KEY=development
      - TZ=Asia/Calcutta
    ports:
      - 127.0.0.1:3000:3000
    expose:
      - 3000
    volumes:
      #- /app/node_modules:/app/node_modules
    networks:
      - workout-tracker-net
  
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    # Also expose the DB on the local machine so that tests can run on it
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - workout-tracker-net
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    networks:
      - workout-tracker-net
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=dev
    depends_on:
      - db

networks:
  workout-tracker-net:
    driver: bridge

volumes:
  db_volume:
    driver: local
  pgadmin_volume:
    driver: local
