services:
  backend:
    build: backend
    command: pnpm dev
    environment:
      - CONNECTION_STRING=postgresql://postgres:dev@db:5432/postgres
    ports:
      - 127.0.0.1:3000:3000
    expose:
      - 3000
    volumes:
      - ./backend:/app
    networks:
      - workout-tracker-net
  
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    networks:
      - workout-tracker-net
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev


networks:
  workout-tracker-net:
    driver: bridge

volumes:
  db_volume:
    driver: local
