services:
  frontend:
    build: frontend
    command: yarn run dev
    ports:
      - 3001:3001
    expose:
      - 3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - fitrack-net

  backend:
    build: backend
    command: yarn run dev
    environment:
      - DB_USERNAME=postgres 
      - DB_PASSWORD=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=wtracker
      - DB_DEFAULT=postgres
      - FASTIFY_PORT=3000
      - FASTIFY_ADDRESS=0.0.0.0
      - JWT_SECRET=development
      - SALT_ROUNDS=10
      - SEED_DB=1
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - fitrack-net

  postgres:
    image: postgres:16-bookworm
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - fitrack-net
    volumes:
      - db:/var/lib/postgresql/data
    restart: always 
    environment:
      POSTGRES_PASSWORD: development
  
  adminer:
    image: adminer
    restart: always
    networks:
      - fitrack-net
    ports:
      - 8080:8080

networks:
  fitrack-net:
    driver: bridge

volumes:
  db:
    driver: local